### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by lawloretienne** [ravidsrk/android-testing-guide#2]
Is this README up to date?  I was just going through it and some of what was there did not seem like the latest ways to do things.  Correct me if i'm wrong though.

**Comment by ravidsrk** [comment]
@lawloretienne Can you point out anything specific you feel outdated?

**Comment by lawloretienne** [comment]
Here is one. Your espresso method names start with test.  I think you can
omit that.

**Comment by ravidsrk** [comment]
@lawloretienne You can open a PR with the updated changes.
